blank_issues_enabled: true
contact_links:
  - name: ❓ Support
    url: https://wpwax.com/helpgent/
    about: For any support or feature request, please head over to our official support channel.
  - name: Documentation
    url: https://wpwax.com/helpgent/
    about: To know more about HelpGent, please check out our official documentation.
